import { fileURLToPath } from 'node:url';
import type { BunSqlDialect } from '#dialect.ts';

// Generated by `bun run generate:fixtures` and committed — never hand-edited.
function fixturePath(dialect: BunSqlDialect): string {
  return fileURLToPath(new URL(`../fixtures/${dialect}-auth-schema.sql`, import.meta.url));
}

export function readFixture(dialect: BunSqlDialect): Promise<string> {
  return Bun.file(fixturePath(dialect)).text();
}

/** Without the generator's header comment: the canonical DDL alone. */
export async function readFixtureDdl(dialect: BunSqlDialect): Promise<string> {
  const text = await readFixture(dialect);
  return text
    .split('\n')
    .filter((line) => !line.startsWith('--'))
    .join('\n')
    .trim();
}
