import { Database } from 'bun:sqlite';
import { join } from 'node:path';
import { getMigrations } from 'better-auth/db/migration';
import { $ } from 'bun';
import { PostgresDialect } from 'kysely';
import { Pool } from 'pg';
import betterAuthPkg from '../node_modules/better-auth/package.json' with { type: 'json' };
import { databaseUrl, POSTGRES_TARGETS } from '../tests/support/postgres.ts';

// The emitted DDL is the same on every Postgres major, so introspect against the
// newest container the test suite runs.
const newestTarget = POSTGRES_TARGETS.at(-1) as (typeof POSTGRES_TARGETS)[number];
const POSTGRES_URL = databaseUrl({ port: newestTarget.port, name: 'postgres' });

const fixturesDir = join(import.meta.dir, '..', 'tests', 'fixtures');
const betterAuthVersion = betterAuthPkg.version;

async function compile(database: unknown): Promise<string> {
  const { compileMigrations } = await getMigrations(database as never);
  return compileMigrations();
}

type FixtureEngine = 'SQLite' | 'Postgres';

async function writeFixture({
  engine,
  ddl,
}: {
  engine: FixtureEngine;
  ddl: string;
}): Promise<void> {
  const header = `-- GENERATED by scripts/generate-auth-schema-fixtures.ts — DO NOT EDIT BY HAND.
-- Canonical better-auth ${engine} core schema, emitted by better-auth@${betterAuthVersion}'s
-- migration generator (the same code path as \`@better-auth/cli generate\`).\n\n`;
  await Bun.write(
    join(fixturesDir, `${engine.toLowerCase()}-auth-schema.sql`),
    `${header}${ddl}\n`,
  );
}

const sqliteDb = new Database(':memory:');
const sqliteDdl = await compile({ database: sqliteDb });
sqliteDb.close();

// Postgres DDL is introspected from a clean Postgres via better-auth's Kysely
// migrator (pg driver) — the same engine the test suite runs against.
await $`docker compose up -d --wait`;
const pool = new Pool({ connectionString: POSTGRES_URL });
let postgresDdl: string;
try {
  postgresDdl = await compile({
    database: { dialect: new PostgresDialect({ pool }), type: 'postgres' },
  });
} finally {
  await pool.end();
  await $`docker compose down -v`;
}

await writeFixture({ engine: 'SQLite', ddl: sqliteDdl });
await writeFixture({ engine: 'Postgres', ddl: postgresDdl });

console.log('✅ Wrote canonical fixtures for better-auth@%s', betterAuthVersion);
