import { Database } from 'bun:sqlite';
import { join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { getMigrations } from 'better-auth/db/migration';
import betterAuthPkg from '../node_modules/better-auth/package.json' with { type: 'json' };
import { pgliteKyselyDialect } from '../tests/support/pglite.ts';

const fixturesDir = join(import.meta.dir, '..', 'tests', 'fixtures');
const betterAuthVersion = betterAuthPkg.version;

async function compile(database: unknown): Promise<string> {
  const { compileMigrations } = await getMigrations(database as never);
  return compileMigrations();
}

type FixtureEngine = 'SQLite' | 'Postgres';

function writeFixture({ engine, ddl }: { engine: FixtureEngine; ddl: string }): Promise<number> {
  const header = `-- GENERATED by scripts/generate-auth-schema-fixtures.ts — DO NOT EDIT BY HAND.
-- Canonical better-auth ${engine} core schema, emitted by better-auth@${betterAuthVersion}'s
-- migration generator (the same code path as \`@better-auth/cli generate\`).\n\n`;
  return Bun.write(
    join(fixturesDir, `${engine.toLowerCase()}-auth-schema.sql`),
    `${header}${ddl}\n`,
  );
}

const sqliteDb = new Database(':memory:');
const sqliteDdl = await compile({ database: sqliteDb });
sqliteDb.close();

const pg = new PGlite();
const postgresDdl = await compile({
  database: { dialect: pgliteKyselyDialect(pg), type: 'postgres' },
});
await pg.close();

await writeFixture({ engine: 'SQLite', ddl: sqliteDdl });
await writeFixture({ engine: 'Postgres', ddl: postgresDdl });

console.log('✅ Wrote canonical fixtures for better-auth@%s', betterAuthVersion);
