import { Database } from 'bun:sqlite';
import { join } from 'node:path';
import { PGlite } from '@electric-sql/pglite';
import { getMigrations } from 'better-auth/db/migration';
import betterAuthPkg from '../node_modules/better-auth/package.json' with { type: 'json' };
import { pgliteKyselyDialect } from '../tests/support/pglite.ts';

const fixturesDir = join(import.meta.dir, '..', 'tests', 'fixtures');
const betterAuthVersion = betterAuthPkg.version;

function header(engine: string): string {
  return `-- GENERATED by scripts/generate-auth-schema-fixtures.ts — DO NOT EDIT BY HAND.
-- Canonical better-auth ${engine} core schema, emitted by better-auth@${betterAuthVersion}'s
-- migration generator (the same code path as \`@better-auth/cli generate\`).\n\n`;
}

async function compile(database: unknown): Promise<string> {
  const { compileMigrations } = await getMigrations(database as never);
  return compileMigrations();
}

const sqliteDb = new Database(':memory:');
const sqliteDdl = await compile({ database: sqliteDb });
sqliteDb.close();

const pg = new PGlite();
const postgresDdl = await compile({
  database: { dialect: pgliteKyselyDialect(pg), type: 'postgres' },
});
await pg.close();

await Bun.write(join(fixturesDir, 'sqlite-auth-schema.sql'), `${header('SQLite')}${sqliteDdl}\n`);
await Bun.write(
  join(fixturesDir, 'postgres-auth-schema.sql'),
  `${header('Postgres')}${postgresDdl}\n`,
);

console.log('✅ Wrote canonical fixtures for better-auth@%s', betterAuthVersion);
